[package]
name = "rock_raiders"
version = "0.1.0"
authors = []

[dependencies]
amethyst = "0.9.0"#{version = "0.9.0" , features = ["nightly"] }
log = "0.4.4"
serde = "1.0.76"
serde_derive = "1.0.76"
collision = "0.18.0"
pathfinding = "1.1.0"
