[package]
name = "rock_raiders"
version = "0.1.0"
authors = []

[dependencies]
amethyst = "0.10.0"#{version = "0.9.0" , features = ["nightly"] }
log = "0.4.6"
serde = "1.0.82"
serde_derive = "1.0.82"
pathfinding = "1.1.4"